### ISSUE TITLE
Unable to create shortcuts

### ISSUE THREAD

**Issue by StormProductionsMusic** [LSPosed/WSAHelper#9]
Hi,

I just discovered this app and am unable to use it. 

Removing shortcuts works, but adding doesn't.

Anyone else having this issue?

WSA version: 207.40000.8.0

**Comment by seamonkey420** [comment]
having same issues. some icons are created ie Playstation App but others like Harmony are not.  Very weird. Same build as you too.

**Comment by LokeYourC3PH** [comment]
Same issue, for me it just closes after clicking the "Create Shortcut" button, not creating shortcuts for any app at all.

Version: 2208.40000.4.0

**Comment by GodSponge** [comment]
Same here. I created an icon for WSAHelper successfully, but now it does absolutely nothing.

edti: I just checked and WSA settings is not showing the apps I installed from the Play store. Possible that it can't make shortcuts to apps installed by the store.

**Comment by lazytiger** [comment]
I have the same error, after upgrade to 2208

```shell
11-08 09:37:17.063 26186 26186 E AndroidRuntime: FATAL EXCEPTION: main
11-08 09:37:17.063 26186 26186 E AndroidRuntime: Process: org.lsposed.wsa.helper, PID: 26186                                                                                                        
11-08 09:37:17.063 26186 26186 E AndroidRuntime: java.lang.NoSuchFieldError: No field MIN_SUPPORTED_TARGET_SDK_INT of type I in class Landroid/os/Build$VERSION; or its superclasses (declaration of 'android.os.Build$VERSION' appears in /system/framework/framework.jar!classes2.dex)                                                                                         
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at com.microsoft.windows.redirection.AppCompat.isPackageNotResizableOverrideNeeded(AppCompat.java:108)                                      
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at com.microsoft.windows.redirection.AppsRedirectionHandler$PackageEventsReceiver.SendNewOrUpdatedAppMessage(AppsRedirectionHandler.java:621)                                                                                    
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at com.microsoft.windows.redirection.AppsRedirectionHandler$PackageEventsReceiver.onReceive(AppsRedirectionHandler.java:598)                
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at org.lsposed.wsa.helper.l.l(Unknown Source:2)                                                                                             
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at G0.a.c(Unknown Source:4)                                                                                                                 
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at kotlinx.coroutines.j.run(Unknown Source:88)                                                                                              
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)                                                                                      
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                      
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)                                                                                
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)                                                                                           
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)                                                        
11-08 09:37:17.063 26186 26186 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)                                                                            
11-08 09:37:17.064   285  5248 W ActivityTaskManager:   Force finishing activity org.lsposed.wsa.helper/.MainActivity                                                                               
11-08 09:37:17.065   598   598 I ShellRedirectionHandler: onTaskInfoChanged taskId: 62
11-08 09:37:17.065 26186 26186 I Process : Sending signal. PID: 26186 SIG: 9
```
